### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by jie-wu1** [sujianqingfeng/Gui-Amazon-Review#1]
你好，抓取的评论为什么都只显示第一行的，后面的很多评论内容都看不见啊？

**Comment by LingHanChuJian** [comment]
你好，问题已经修复了， 请下载最新版试试

**Comment by LingHanChuJian** [comment]
@jie-wu1

**Comment by jie-wu1** [comment]
非常感谢，已经试用，可以获得完整评论了




------------------ 原始邮件 ------------------
发件人: "Linghanchujian"<notifications@github.com>;
发送时间: 2019年5月23日(星期四) 晚上8:43
收件人: "sujianqingfeng/Gui-Amazon-Review"<Gui-Amazon-Review@noreply.github.com>;
抄送: "609159155"<609159155@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sujianqingfeng/Gui-Amazon-Review] 你好 (#1)




你好，问题已经修复了， 请下载最新版试试
